# -*- coding: utf-8 -*-
"""2° Trabalho de Introdução à Modelagem Econômica e Ciência de Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-JyEC5IZguviauemvXTbMExL9emngMG

#2° Trabalho de Introdução à Modelagem Econômica e Ciência de Dados

  Você foi contratado para desenvolver um sistema de gerenciamento de estoque, clientes e vendas para uma livraria. O sistema deve permitir visualizar e filtrar informações sobre livros, clientes e vendas de forma dinâmica, além de fornecer insights sobre as aquisições, gastos dos clientes e quantidades de livros vendidos.

####Tarefas:

1. Criação de Bancos de Dados SQLite:
  i. Crie três bancos de dados SQLite: `livros.db`, `clientes.db` e `vendas.db`.
  ii. No banco de dados `livros.db`, crie uma tabela chamada `livros` com as seguintes colunas:
       -  `id_livro`: inteiro, chave primária
       -  `titulo`: texto
       -  `autor`: texto
       -  `genero`: texto
       -  `preco`: real
  iii. No banco de dados `clientes.db`, crie uma tabela chamada `clientes` com as seguintes colunas:
       -  `id_cliente`: inteiro, chave primária
       -  `nome`: texto
       -  `email`: texto
       - `telefone`: texto
  iv. No banco de dados `vendas.db`, crie uma tabela chamada `vendas` com as seguintes colunas:
       -  `id_venda`: inteiro, chave primária
       -  `id_cliente`: inteiro, chave estrangeira referenciando `clientes(id_cliente)`
       -  `id_livro`: inteiro, chave estrangeira referenciando `livros(id_livro)`
       -  `quantidade`: inteiro, indicando a quantidade de livros adquirida pelo cliente
  v. Insira alguns dados de exemplo em todas as tabelas.

2. Leitura e Integração de Dados com Pandas:
  i. Utilize a biblioteca `pandas` para ler os dados das tabelas `livros`, `clientes` e `vendas` dos respectivos bancos de dados.
  ii. Crie três DataFrames: `df_livros`, `df_clientes` e `df_vendas`.
  iii. Integre os três DataFrames em um único DataFrame chamado `df_completo` utilizando as colunas `id_cliente` e `id_livro` como chaves de junção.

3. Criação de um Aplicativo Streamlit:
  i. Utilize a biblioteca `streamlit` para criar um aplicativo web interativo.
  ii. Exiba o DataFrame `df_completo` no aplicativo.
  iii. Implemente filtros dinâmicos para as colunas do DataFrame, permitindo ao usuário filtrar os dados por:
      -  Livros: título, autor, gênero e faixa de preço.
      -  Clientes: nome, email e telefone.
      -  Vendas: quantidade de livros adquirida, data da venda (se aplicável).
  iv. Crie visualizações e dashboards que permitam analisar:
      -  Aquisicoes e Gastos dos Clientes: total gasto por cliente, livros mais comprados por cliente, etc.
      -  Quantidades de Livros Vendidos: total de vendas por livro, livros mais vendidos, etc.
      - Exiba os dados filtrados e as visualizações no aplicativo.

Requisitos Adicionais:

  i.  Utilize ao menos as bibliotecas `sqlite3`, `pandas` e `streamlit`.
  ii.  O código deve ser bem documentado e organizado.
  iii.  O aplicativo Streamlit deve ter uma interface intuitiva e fácil de usar.
  iv.  As visualizações e dashboards devem ser informativos e apresentar os dados de forma clara.

Objetivo:

Desenvolver um sistema funcional que permita a gestão completa da livraria, incluindo visualização e filtragem de informações sobre livros, clientes e vendas, além de fornecer insights relevantes para a tomada de decisões.

Observações:

  i. Este enunciado pode ser adaptado para incluir funcionalidades adicionais, como cadastro de novos livros e clientes, edição de informações existentes e geração de relatórios mais complexos.
  ii. A criatividade na implementação da interface do aplicativo Streamlit e na criação das visualizações é encorajada e valorizará a avaliação.

##Instalação dos programas necessários
"""

!pip install --upgrade streamlit
!pip install streamlit pandas -g
!npm install localtunnel

"""##Codigo do site da livraria

"""

import streamlit as st
import pandas as pd
import sqlite3
from datetime import datetime

# 1. Configuração dos Bancos de Dados ==========================================
def criar_bancos():
    # Criar e popular tabelas
    for db, schema in [('livros.db', '''
                        CREATE TABLE IF NOT EXISTS livros (
                            id_livro INTEGER PRIMARY KEY,
                            titulo TEXT,
                            autor TEXT,
                            genero TEXT,
                            preco REAL)'''),
                       ('clientes.db', '''
                        CREATE TABLE IF NOT EXISTS clientes (
                            id_cliente INTEGER PRIMARY KEY,
                            nome TEXT,
                            email TEXT,
                            telefone TEXT)'''),
                       ('vendas.db', '''
                        CREATE TABLE IF NOT EXISTS vendas (
                            id_venda INTEGER PRIMARY KEY,
                            id_cliente INTEGER,
                            id_livro INTEGER,
                            quantidade INTEGER,
                            data_venda DATE)''')]:
        conn = sqlite3.connect(db)
        conn.execute(schema)
        conn.commit()
        conn.close()

    # Inserir dados de exemplo
    exemplos = {
        'livros.db': [
            (1, 'Dom Casmurro', 'Machado de Assis', 'Clássico', 45.90),
            (2, '1984', 'George Orwell', 'Ficção Distópica', 37.50),
            (3, 'Clean Code', 'Robert C. Martin', 'Tecnologia', 89.90)
        ],
        'clientes.db': [
            (1, 'João Silva', 'joao@email.com', '(11) 9999-8888'),
            (2, 'Maria Souza', 'maria@email.com', '(21) 7777-6666')
        ],
       'vendas.db': [
        (1, 1, 1, 2, datetime.strptime('2024-01-15', '%Y-%m-%d').strftime('%Y-%m-%d')),
        (2, 2, 2, 1, datetime.strptime('2024-02-01', '%Y-%m-%d').strftime('%Y-%m-%d')),
        (3, 1, 3, 1, datetime.strptime('2024-02-10', '%Y-%m-%d').strftime('%Y-%m-%d'))
        ],
    }

    for db, dados in exemplos.items():
        conn = sqlite3.connect(db)
        cursor = conn.cursor()
        tabela = db.split('.')[0]
        cursor.executemany(f'INSERT OR IGNORE INTO {tabela} VALUES ({",".join(["?"]*len(dados[0]))})', dados)
        conn.commit()
        conn.close()

# 2. Integração de Dados ======================================================
@st.cache_data
def carregar_dados():
    dfs = {}
    for db in ['livros.db', 'clientes.db', 'vendas.db']:
        conn = sqlite3.connect(db)
        tabela = db.split('.')[0]
        dfs[tabela] = pd.read_sql_query(f"SELECT * FROM {tabela}", conn)
        conn.close()

    df_completo = dfs['vendas'].merge(dfs['clientes'], on='id_cliente')\
                               .merge(dfs['livros'], on='id_livro')
    df_completo['total_venda'] = df_completo['preco'] * df_completo['quantidade']
    return df_completo

# 3. Interface Streamlit ======================================================
def main():
    st.set_page_config(page_title="Gestão de Livraria", layout="wide")
    criar_bancos()
    df = carregar_dados()

    # Sidebar - Filtros
    st.sidebar.header("Filtros Avançados")

    # Filtros de Livros
    generos = ['Todos'] + df['genero'].unique().tolist()
    genero_selecionado = st.sidebar.selectbox('Gênero Literário', generos)

    faixa_preco = st.sidebar.slider('Faixa de Preço (R$)',
                                  float(df['preco'].min()),
                                  float(df['preco'].max()),
                                  (0.0, 100.0))

    # Filtros de Clientes
    cliente_selecionado = st.sidebar.multiselect('Clientes',
                                                df['nome'].unique())

    # Filtros de Vendas
    data_min = pd.to_datetime(df['data_venda']).min().date()
    data_max = pd.to_datetime(df['data_venda']).max().date()
    datas_selecionadas = st.sidebar.date_input('Período das Vendas',
                                             [data_min, data_max])

    # Aplicar Filtros
    df_filtrado = df.copy()
    if genero_selecionado != 'Todos':
        df_filtrado = df_filtrado[df_filtrado['genero'] == genero_selecionado]

    df_filtrado = df_filtrado[(df_filtrado['preco'] >= faixa_preco[0]) &
                            (df_filtrado['preco'] <= faixa_preco[1])]

    if cliente_selecionado:
        df_filtrado = df_filtrado[df_filtrado['nome'].isin(cliente_selecionado)]

    df_filtrado = df_filtrado[(df_filtrado['data_venda'] >= str(datas_selecionadas[0])) &
                            (df_filtrado['data_venda'] <= str(datas_selecionadas[1]))]

    # Visualização Principal
    st.title("📊 Dashboard de Gestão de Livraria")

    # Métricas Principais
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Total de Vendas", f"R$ {df_filtrado['total_venda'].sum():.2f}")
    with col2:
        st.metric("Livros Vendidos", df_filtrado['quantidade'].sum())
    with col3:
        st.metric("Clientes Únicos", df_filtrado['id_cliente'].nunique())

    # Visualizações Gráficas
    tab1, tab2, tab3 = st.tabs(["Análise de Vendas", "Desempenho de Livros", "Comportamento do Cliente"])

    with tab1:
        st.subheader("Vendas por Período")
        vendas_por_data = df_filtrado.groupby('data_venda')['total_venda'].sum()
        st.line_chart(vendas_por_data)

    with tab2:
        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Top 5 Livros Mais Vendidos")
            top_livros = df_filtrado.groupby('titulo')['quantidade'].sum().nlargest(5)
            st.bar_chart(top_livros)

        with col2:
            st.subheader("Distribuição por Gênero")
            generos = df_filtrado.groupby('genero')['quantidade'].sum()
            fig = generos.plot.pie(autopct='%1.1f%%', ylabel='').figure
            st.pyplot(fig)

    with tab3:
        st.subheader("Gasto Total por Cliente")
        gasto_cliente = df_filtrado.groupby('nome')['total_venda'].sum().sort_values(ascending=False)
        st.bar_chart(gasto_cliente)

    # Tabela de Dados
    st.subheader("Detalhes das Vendas")
    st.dataframe(df_filtrado.style.format({'preco': 'R$ {:.2f}', 'total_venda': 'R$ {:.2f}'}),
                height=400,
                use_container_width=True)

if __name__ == "__main__":
    main()

"""##Execução do app no Streamlit

"""

!streamlit run app_livraria.py & npx localtunnel --port 8501